# Generated by Django 2.0.6 on 2018-07-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno_firmy', models.CharField(help_text='Nazov firmy', max_length=20, verbose_name='menoFirmy')),
                ('konatel', models.CharField(help_text='Konatel', max_length=40, verbose_name='Konatel')),
                ('adresa1', models.CharField(help_text='Adresa1', max_length=40, verbose_name='Adresa1')),
                ('adresa2', models.CharField(help_text='Adresa2', max_length=40, verbose_name='Adresa2')),
                ('psc', models.CharField(help_text='PSC', max_length=40, verbose_name='PSC')),
                ('krajina', models.CharField(help_text='krajina', max_length=40, verbose_name='krajina')),
                ('telefon', models.CharField(help_text='telefon', max_length=40, verbose_name='telefon')),
                ('email', models.EmailField(help_text='email', max_length=254, verbose_name='email')),
            ],
        ),
    ]
