# Generated by Django 2.0.6 on 2018-08-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='konatel1',
            field=models.CharField(default='', help_text='Konatel Alt', max_length=40, verbose_name='Konatel Alt'),
        ),
        migrations.AddField(
            model_name='firma',
            name='telefon1',
            field=models.CharField(default='', help_text='telefon1', max_length=40, verbose_name='telefon1'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='adresa1',
            field=models.CharField(default='', help_text='Adresa1', max_length=40, verbose_name='Adresa1'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='adresa2',
            field=models.CharField(default='', help_text='Adresa2', max_length=40, verbose_name='Adresa2'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='konatel',
            field=models.CharField(default='', help_text='Konatel', max_length=40, verbose_name='Konatel'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='krajina',
            field=models.CharField(default='', help_text='krajina', max_length=40, verbose_name='krajina'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='meno_firmy',
            field=models.CharField(default='', help_text='Nazov firmy', max_length=20, verbose_name='menoFirmy'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='psc',
            field=models.CharField(default='', help_text='PSC', max_length=40, verbose_name='PSC'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='telefon',
            field=models.CharField(default='', help_text='telefon', max_length=40, verbose_name='telefon'),
        ),
    ]
